- name: "Playbook variable"
  hosts: local
  connection: local
  vars:
    Course: Devops
    Trainer: Dinesh
    Duration: 10Hrs
  tasks:
  - name: Execution of variables from Playbook
    vars:
      Course: Devops with AWS
      Trainer: Dinesh Reddy Gadila
    ansible.builtin.debug:
      msg: "couse name is {{Course}}, Trainer is {{Trainer}}, Duration of Course is {{Duration}}"
